### ISSUE TITLE
eslint-plugin-autofix bug

### ISSUE THREAD

**Issue by rowrowrowrow** [aladdin-add/eslint-plugin#64] opened 2020-03-11 17:40 UTC
**Tell us about your environment**

* **eslint version:**

"^6.8.0"

* **eslint-plugin-autofix version:**

"^1.0.0"

* **eslint config:**

module.exports = {
  "extends": ["react-app", "plugin:jsx-a11y/recommended"],
  "plugins": ["autofix", "jsx-a11y"],
  "rules": {
    "autofix/no-debugger": "error",
    "autofix/no-console": "error",
    "autofix/no-plusplus": "error",
    "autofix/no-unused-vars": "warn",
  }
}

**Expected behavior**

run: 'eslint src' or 'eslint src --fix'
expectation: Autofixes according to the defined rules

**Actual behavior**

typeError: Cannot read property 'range' of null
Occurs while linting.....

Note: I've tried each plugin individually and it occurs for each plugin. I've tried other plugins and the error doesn't occur.

**Comment by aladdin-add** [comment] 2020-06-23 03:38
hi, sorry for the late! can you share your source code?

**Comment by MaffooBristol** [comment] 2020-07-13 14:37
I also have this issue, I believe it was introduced by later versions of babel-eslint and perhaps due to duplicated instances of `@babel/types`

**Comment by aladdin-add** [comment] 2020-07-13 15:23
sounds like that way. an example code can be helpful!

**Comment by giuliano-december** [comment] 2020-12-23 14:04
@aladdin-add  I'm having the same problem. Seems like the problem is unused function parameters:

```
// exits with error: typeError: Cannot read property 'range' of null
export const startToolExercise = async (toolId: number): Promise<string> => {
  return '1'
}

// works fine
export const startToolExercise = async (toolId: number): Promise<string> => {
  toolId;
  return '1'
}
```js

**Comment by aladdin-add** [comment] 2020-12-30 06:13
I'm going to close the issue, as @MaffooBristol  [mentioned](https://github.com/aladdin-add/eslint-plugin/issues/64#issuecomment-657599021) :the error is something related with babel-eslint, but not related to the plugin. 

please upgrade to latest babel-eslint => [@babel/eslint-parser](https://www.npmjs.com/package/@babel/eslint-parser) to see if it has been fixed!

**Closed by aladdin-add** 2020-12-30 06:13 UTC
Labels: bug
